server:
  port: 8080
  servlet:
    context-path: /AuthCenter

logging:
  level:
    org.springframework.web: DEBUG
    com.iemp.auth.authcenter: DEBUG
mybatis:
  type-aliases-package: com.iemp.auth.authcenter.domain
  config-locations:  mybatis/mybatis-config.xml
  mapper-locations:  mybatis/mapper/*.xml
  configuration:
      call-setters-on-nulls: true

#############本地服务器##############
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iemp?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
#############################################redis的配置信息##############################################
  redis:
#redis的地址
    host: 127.0.0.1
#redis的端口
    port: 123456
#redis的数据库索引
    database: 1
#服务器的链接密码(默认为空)
    password: Changeme_123
#链接超时时间
    timeout: 10000
