server:
  port: 8080
  servlet:
    context-path: /AuthCenter

logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG
mybatis:
  type-aliases-package: com.iemp.auth.authcenter.domain
  config-locations:  mybatis/mybatis-config.xml
  mapper-locations:  mybatis/mapper/*.xml
  configuration:
      call-setters-on-nulls: true

#############本地服务器##############
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root

